#!/bin/sh

APP=blackflow

DIR=/usr/lib/${APP}
DAEMON=/usr/lib/${APP}/blackflow_service.py
DAEMON_NAME=${APP}
PYTHON_BIN=/usr/bin/python
PARAMETERS=$@

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --pidfile $PIDFILE --background --make-pidfile --user $DAEMON_USER --chdir $DIR --chuid $DAEMON_USER --startas $PYTHON_BIN $DAEMON
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}
case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    debug)
        ${DAEMON}
        ;;

    *)
        echo "Unrecognized parameter(s): \"$@\"" >/dev/stderr; exit 1

esac
exit 0
