#!/bin/sh
### BEGIN INIT INFO
# Provides:          zwta
# Required-Start:    mosquitto $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script for controlling devicereg service
# Description:       The script support start|stop|restart operations, and has a debug mode which is run in foreground
### END INIT INFO

APP=zwta

# Create directories
mkdir /media/app/${APP} >/dev/null 2>&1
mkdir /etc/smartly/${APP} >/dev/null 2>&1
mkdir /var/log/smartly/${APP} >/dev/null 2>&1

DIR=/media/app/${APP}
DAEMON=/usr/lib/lyse_services/${APP}/bin/main.py
DAEMON_NAME=${APP}
PYTHON_BIN=/usr/bin/python
PARAMETERS=$@

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --pidfile $PIDFILE --background --make-pidfile --user $DAEMON_USER --chdir $DIR --chuid $DAEMON_USER --startas $PYTHON_BIN $DAEMON
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}
case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    debug)
        ${DAEMON}
        ;;

    *)
        echo "Unrecognized parameter(s): \"$@\"" >/dev/stderr; exit 1

esac
exit 0
