#!/bin/sh
APP=zwta

# Compile python sources
python -m compileall /usr/lib/lyse_services/${APP}/bin || :

# Create directory
mkdir -p /media/app/${APP} 2>/dev/null || :

# Install service
update-rc.d -f ${APP} remove
update-rc.d ${APP} defaults 30
service ${APP} start
