#!/bin/sh
APP=blackflow

# Create directory
mkdir -p /var/lib/blackflow/apps/lib 2>/dev/null || :
mkdir -p /var/lib/blackflow/apps/data 2>/dev/null || :
mkdir -p /var/log/blackflow/ 2>/dev/null || :
touch /var/lib/blackflow/apps/__init__.py
touch /var/lib/blackflow/apps/lib/__init__.py

# Install service
#chmod a+x /etc/init.d/blackflow
#update-rc.d -f ${APP} remove
#update-rc.d ${APP} defaults 30
#service ${APP} start
systemctl enable ${APP}
systemctl start ${APP}