#!/bin/sh
APP=blackflow

# Create directory
mkdir -p /var/blackflow/apps/lib 2>/dev/null || :
mkdir -p /var/log/blackflow/ 2>/dev/null || :


# Install service
chmod a+x /etc/init.d/blackflow
update-rc.d -f ${APP} remove
update-rc.d ${APP} defaults 30
service ${APP} start
